mp3/urls.py
from django.conf.urls import url
from . import views

app_name = 'mp3'

urlpatterns = [
    #/mp3/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #/mp3/PK/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #mp3/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    #mp3/album/pk/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    #mp3/album/pk/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

]

mp3/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=300)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('mp3:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

mp3/views.py
from django.views import generic
from .models import Album
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class IndexView(generic.ListView):
    template_name = 'mp3/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'mp3/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('mp3:index')

mp3/templates/mp3/album_form.html
{% extends 'mp3/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class = "container-fluid">

  <div class = "row">

    <div class = "col-sm-12 col-md-7">
      <div class = "panel panel-default">
        <div class = "panel-body">

          <form class="form-horizontal" action="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {% include 'mp3/form-template.html' %}
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-success">Submit</button>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mp3/templates/mp3/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Tamil mp3 Cloud{% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <link rel="stylesheet" type"text/css" href="{% static 'mp3/style.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajas/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">


      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'mp3:index' %}">Tamil mp3 Cloud</a>
      </div>
      <!--items -->
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li class="active">
            <a href="{% url 'mp3:index' %}">
              <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
            </a>
          </li>
          <li class="">
            <a href="#">
              <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
            </a>
          </li>
        </ul>

        <form class="navbar-form navbar-left" role="search" method="get" action="#">
          <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <li class="">
            <a href"{% url 'mp3:album-add' %}">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
            </a>
          </li>
          <li class="">
            <a href"#">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
            </a>
          </li>
        </ul>

      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
</body>
</html>

mp3/templates/mp3/detail.html
{% extends 'mp3/base.html' %}
{% block title %}Album list{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
  <div class="container-fluid songs-container">
    <div class="row">

      <!-- Left Alubum info-->
      <div class="col-sm-4 col-md-3">
        <div class="panel panel-default">
          <div class="panel-body">
            <a href="{% url 'mp3:detail' album.id %}">
              <img src="{{ album.album_logo }}" class="img-responsive">
            </a>

            <h1>{{ album.album_title }}
              <small>{{ album.genre }}</small>
            </h1>
            <h3>{{ album.artist }}</h3>
          </div>
        </div>
      </div>

      <!--Right Song Info -->
      <div class="col-sm-8 col-md-9">

        <ul class="nav nav-pills" style="margin-bottom: 10px;">
          <li class="active"><a href="{% url 'mp3:detail' album.id %}">View All</a></li>
          <li><a href="#">Add New Song</a></li>
        </ul>

        <div class="panel panel-default">
          <div class="panel-body">

            <h3>All Songs</h3>

            <table class="table">
              <thead>
              <tr>
                <th>Title</th>
                <th>Audio File</th>
                <th>favorite</th>
                <th>Action</th>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

mp3/templates/mp3/form-template.html
{% for field in form %}
  <div class="form-group">
    <def class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{ field.errors }}</span>
    </def>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

mp3/templates/mp3/index.html
{% extends 'mp3/base.html' %}
{% block album_active %}active{% endblock %}

{% block body %}
  <div class="album-container container-fluid">
    <div class="row">
      {% for album in all_albums %}
        <div class="col-sm-4 col-lg-2">
          <div class="thumbnail">
            <!--Album logo-->
            <a href="{% url 'mp3:detail' album.id %}">
              <img src="{{ album.album_logo }}" class="img-responsive">
            </a>
            <div class="caption">
              <h2>{{ album.album_title }}</h2>
              <h3>{{ album.artist }}</h3>

              <!--Deatils-->
              <a href="{% url 'mp3:detail' album.id %}" class="btn btn-primary btn-sm">View Details</a>
              <!--Delete-->
              <form action="{% url 'mp3:album-delete' album.id %}" method="post" >
                {% csrf_token %}
                <input type="hidden" name="album_id" value="{{ album.id }}"/>
                <button type="submit" class="btn btn-default btn-sm">
                  <span class="glyphicon glyphicon-trash"></span>
                </button>
              </form>
              <!-- favorite-->
              <a href="#" class="btn btn-default btn-sm btn-favorite">
                <span class="glyphicon glyphicon-star{% if album.is_favorite %}active{% endif %}"></span>
              </a>

            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}